import os
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import joblib
from prophet import Prophet

# ==========================================
# 1. PAGE CONFIG & ARCHITECTURE SETUP
# ==========================================
st.set_page_config(page_title="Electricity Demand XAI Dashboard", layout="wide")
st.title("⚡ Grid Demand Forecasting & Anomaly Detection")
st.markdown("""
This dashboard demonstrates a three-tier hybrid architecture: 
**Prophet** for structural baselines, **LightGBM** for weather/macro-driven residuals, and **Isolation Forest** for black-swan anomaly detection.
""")

# Setup relative paths so it runs anywhere
script_dir = os.path.dirname(os.path.abspath(__file__))
models_dir = os.path.join(script_dir, 'Models')
data_path = os.path.join(script_dir, 'Outputs', 'dataset_daily_with_predictions.csv')

# ==========================================
# 2. CACHED DATA & MODEL LOADING
# ==========================================
@st.cache_resource
def load_models():
    prophet_model = joblib.load(os.path.join(models_dir, 'prophet_model.joblib'))
    lgbm_model = joblib.load(os.path.join(models_dir, 'lgbm_model.joblib'))
    iso_forest = joblib.load(os.path.join(models_dir, 'iso_forest.joblib'))
    return prophet_model, lgbm_model, iso_forest

@st.cache_data
def load_and_prep_data():
    # Read the NEW file generated by the training script
    df = pd.read_csv(data_path)
    df['Date'] = pd.to_datetime(df['Date'])
    return df

try:
    prophet_model, lgbm_model, iso_forest = load_models()
    df = load_and_prep_data()
except FileNotFoundError as e:
    st.error(f"Missing required file: {e}")
    st.stop()

# ==========================================
# 3. COMPONENT 1: SYSTEM VALIDATION & ANOMALIES
# ==========================================
st.header("1. System Validation & Anomaly Detection")
st.markdown("*Tracking actual demand against the hybrid prediction, with Isolation Forest flagging structural grid failures.*")

# The exact 12 features the IsoForest was trained on
iso_features = [
    'Day_of_Week', 'Is_Weekend', 'Is_Holiday', 
    'Avg_Temp', 'Rainfall', 
    'Lag_1', 'Lag_7', 'Lag_30', 'Rolling_7',
    'GDP', 'Population', 'Industrial_Index'
]

# Ensure we only predict on rows that have all features (no NaNs from lags)
df_clean = df.dropna(subset=iso_features + ['Demand_MWh', 'Hybrid_Prediction']).copy()

# Predict Anomalies (-1 is anomaly, 1 is normal)
df_clean['Anomaly_Score'] = iso_forest.predict(df_clean[iso_features])
anomalies = df_clean[df_clean['Anomaly_Score'] == -1]

# Build Plotly Chart
fig_main = go.Figure()
fig_main.add_trace(go.Scatter(x=df_clean['Date'], y=df_clean['Demand_MWh'], mode='lines', name='Actual Demand', line=dict(color='blue')))
fig_main.add_trace(go.Scatter(x=df_clean['Date'], y=df_clean['Hybrid_Prediction'], mode='lines', name='Hybrid Prediction', line=dict(color='orange', dash='dash')))
fig_main.add_trace(go.Scatter(
    x=anomalies['Date'], y=anomalies['Demand_MWh'], mode='markers', name='Grid Anomaly Detected',
    marker=dict(color='red', size=10, symbol='x', line=dict(color='black', width=1)),
    hovertemplate="<b>Date:</b> %{x}<br><b>Demand:</b> %{y}<extra>Anomaly</extra>"
))
fig_main.update_layout(height=500, template='plotly_white', hovermode='x unified')
st.plotly_chart(fig_main, use_container_width=True)

st.divider()

# ==========================================
# 4. COMPONENT 2: THE STRUCTURAL BASELINE
# ==========================================
st.header("2. The Structural Baseline (Prophet)")
st.markdown("*Prophet extracts the core mathematical rhythm of the grid—isolating the overall trend and weekly seasonality independently of weather.*")

col1, col2 = st.columns([1, 1])

with col1:
    df_prophet = df_clean[['Date']].rename(columns={'Date': 'ds'})
    forecast = prophet_model.predict(df_prophet)
    
    fig_prophet = prophet_model.plot_components(forecast)
    st.pyplot(fig_prophet)

# ==========================================
# 5. COMPONENT 3: EXOGENOUS IMPACT (SHAP)
# ==========================================
with col2:
    st.header("3. Exogenous Factor Impact")
    st.markdown("*While Prophet sets the baseline, LightGBM calculates the exact MWh impact of weather, schedules, and macroeconomics.*")
    
    # Displaying your pre-rendered SHAP plot is safest for live demos
    try:
        st.image("output_xai.png", caption="Global SHAP Summary for Exogenous Features", use_container_width=True)
    except Exception:
        st.info("ℹ️ SHAP visualization not available. Generate it by running `Scripts/hybrid_model.py` to create the XAI analysis plot.")