version: '3.8'

services:
  api:
    image: ghcr.io/ucyenyen/finditdataset:${IMAGE_TAG:-latest}
    pull_policy: always
    container_name: findit_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=8000
    expose:
      - "8000"
    networks:
      - global_proxy

networks:
  global_proxy:
    external: true
